class CartLocators:
    click_cart_locator_text_Id = "cartur"
    click_place_order_button_xpath = "/html[1]/body[1]/div[6]/div[1]/div[2]/button[1]"
    enter_name_of_place_order_id = "name"
    enter_country_of_place_order_id = "country"
    enter_place_order_city_id = "city"
    enter_credit_card_id = "card"
    enter_place_month_id = "month"
    enter_place_order_year_id = "year"
    click_purchase_place_order_xpath = "/html[1]/body[1]/div[3]/div[1]/div[1]/div[3]/button[2]"