class LaptopsLocators:
    click_home_text_xpath = "/html[1]/body[1]/nav[1]/div[1]/ul[1]/li[1]/a[1]"
    click_back_role_button_slide_xpath = "/html[1]/body[1]/nav[1]/div[2]/div[1]/a[2]"
    click_next_role_button_slide_xpath = "/html[1]/body[1]/nav[1]/div[2]/div[1]/a[2]"
    click_CATAGORIES_text_xpath = "//a[@id='cat']"
    click_laptops_text_xpath = "//a[contains(text(),'Laptops')]"
    click_laptops_sony_vaio_i5_xpath = "//a[contains(text(),'Sony vaio i5')]"
    click_add_to_cart_xpath = "//a[contains(text(),'Add to cart')]"
    click_cart_text_xpath= "/html[1]/body[1]/nav[1]/div[1]/div[1]/ul[1]/li[4]"
    click_place_order_xpath = "//button[contains(text(),'Place Order')]"
    enter_name_of_place_order_id = "name"
    enter_country_of_place_order_id = "country"
    enter_place_order_city_id = "city"
    enter_credit_card_id = "card"
    enter_place_month_id = "month"
    enter_place_order_year_id = "year"
    click_purchase_place_order_xpath = "/html[1]/body[1]/div[3]/div[1]/div[1]/div[3]/button[2]"
    click_ok_purchase_xpath = "/html[1]/body[1]/div[10]/div[7]/div[1]"
    click_cloth_purchase_xpath = "/html[1]/body[1]/div[3]/div[1]/div[1]/div[3]/button[1]"
